import type { Metadata } from "next";
import { Poppins, Quicksand } from 'next/font/google';

const poppins = Poppins({ subsets: ['latin'], weight: ['400', '700'] });
const quicksand = Quicksand({ subsets: ['latin'] });

const poppinsSans = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "700"], // 👈 Adicionado
});

const quicksMono = Quicksand({
  variable: "--font-quicksand-mono",
  subsets: ["latin"],
  weight: ["400", "700"], // 👈 Adicionado
});

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppinsSans.variable} ${quicksMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
